### PR TITLE
Fix multi-query opts decode

### LINKED ISSUE #50: Multi-query opts key needs to be decoded to keyword
Currently `"opts"` in JSON multi-query requests doesn't get decoded to a keyword because the multi-query schema assumes every top-level key is a user-defined query-results identifier key. But it needs to be a keyword for db to recognize it.

### PR DESCRIPTION
**Pull request by cap10morgan**
Closes #50 

Builds on top of #51 so probably review that first.

### CODE REVIEW

File: test/fluree/http_api/system_test.clj [hunk 1]
```diff
@@ -297,67 +309,120 @@
...
+             ["f:v"]                 nat-int?
+             ["f:data" "f:address"]  #(re-matches mem-addr-regex %)
+             ["f:data" "f:assert"]   #(and (vector? %) (every? map? %))
+             ["f:data" "f:retract"]  #(and (vector? %) (every? map? %))
+             ["f:data" "f:flakes"]   pos-int?
+             ["f:data" "f:size"]     pos-int?
+             ["f:data" "f:t"]        pos-int?
+             ["f:data" "f:previous"] #(or (nil? %)
+                                          (re-matches db-id-regex (get % "id")))}]
+        (is (every? #(every? (fn [[kp valid?]]
```
Comment (zonotope) [inline test/fluree/http_api/system_test.clj:360]: Perhaps you could use the built-in [clojure.test `are` macro](https://clojuredocs.org/clojure.test/are) for this.

**Review by zonotope — APPROVED** [review]
I have one suggestion to clean up the tests for clarity, but there's a chance it either might not work or might not be clearer in practice.

File: test/fluree/http_api/system_test.clj (hunk 1 above)
Comment (cap10morgan) [reply test/fluree/http_api/system_test.clj:360]: Yeah, I started with that at one point. There's probably still a better refactoring of this involving that but it wasn't jumping out at me. The wrinkle was the `(every? #(every? ...))` construction and being careful not to make assertions I didn't mean (e.g. it's easy to accidentally make the assertion that every key in the actual is one of the keys in an expected set using the set-as-pred pattern; but that will cause empty / strict-subset map actuals to pass).

Comment (dpetran) [reply test/fluree/http_api/system_test.clj:360]: I'm generally not a fan of `are` because if it fails it won't tell you which case actually failed. It's more laborious to use `is` for every case, but working with it later is a lot easier.
